# Core
db:
  redis:
    emulate: true
    namespace: EG

plugins:
  jwt-custom1:
      package: "./lib/express-gateway-plugin-jwt-custom1/manifest.js"
      secretKey: "secretAuth"
      jwtExtractor: "authBearer"
      messageErr: "Token anda sudah kadaluarsa bro"

crypto:
  cipherKey: sensitiveKey
  algorithm: aes256
  saltRounds: 10

# OAuth2 Settings
session:
  secret: keyboard cat
  resave: false
  saveUninitialized: false
accessTokens:
  timeToExpiry: 7200000
refreshTokens:
  timeToExpiry: 7200000
authorizationCodes:
  timeToExpiry: 300000
