version: '3'

services:

  egateway:
    hostname: 127.0.0.1
    container_name: egateway
    build: './test-eg2'
    ports: 
      - "8080:8080"
    depends_on: 
      - mongo
    environment: 
      - LOG_LEVEL=debug

  api-auth:
    container_name: api-auth
    build: './api-auth'
    ports: 
      - "3003:3003"
    links: 
      - mongo
      - egateway

  api-crud:
    container_name: api-crud
    build: './api-crud'
    ports: 
      - "3004:3004"
    links: 
      - mongo
      - egateway

  react-client:
    container_name: react-client
    build: './0-react-client'
    ports: 
      - "3000:3000"
    links: 
      - mongo
      - egateway
      - api-auth
      - api-crud

  mongo:
    container_name: mongo-dbx
    image: mongo
    ports: 
      - "27017:27017"