export const AUTH_SIGN_UP = 'AUTH_SIGN_UP';
export const AUTH_SIGN_IN = 'AUTH_SIGN_IN';
export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT';
export const AUTH_ERROR = 'AUTH_ERROR';
export const DASHBOARD_GET_DATA = 'DASHBOARD_GET_DATA';
export const AUTH_SET_SECRET = 'AUTH_SET_SECRET';
export const AUTH_UPDATE_SELF_USER = 'AUTH_UPDATE_SELF_USER';

export const USER_GET_DATA = 'USER_GET_DATA';
export const USER_DELETE_DATA = 'USER_DELETE_DATA';
export const USER_ADD_DATA = 'USER_ADD_DATA';
export const USER_GET_ONE_DATA = 'USER_GET_ONE_DATA';
export const USER_UPDATE_DATA = 'USER_UPDATE_DATA';
export const USER_UPDATE_PASS_DATA = 'USER_UPDATE_PASS_DATA';

export const ERROR_USER_GET_DATA = 'ERROR_USER_GET_DATA';
export const ERROR_USER_DELETE_DATA = 'ERROR_USER_DELETE_DATA';
export const ERROR_USER_UPDATE_DATA = 'ERROR_USER_UPDATE_DATA';
export const ERROR_USER_ADD_DATA = 'ERROR_USER_ADD_DATA';
export const ERROR_USER_GET_ONE_DATA = 'ERROR_USER_GET_ONE_DATA';
export const ERROR_USER_UPDATE_PASS_DATA = 'ERROR_USER_UPDATE_PASS_DATA';